# Generated by Django 3.2.19 on 2023-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='xml',
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
