# Generated by Django 3.2.19 on 2023-07-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvmapp', '0002_auto_20230707_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='state',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
