# Generated by Django 3.2.19 on 2023-07-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvmapp', '0003_auto_20230707_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
